In [2]:
import torch

### 基本用法

使用empty生成五行三列的矩阵

In [3]:
x = torch.empty(5 , 3)
x

tensor([[8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39]])

In [5]:
x = torch.rand(5 , 3)
x

tensor([[0.3269, 0.2083, 0.4061],
        [0.5898, 0.9194, 0.1332],
        [0.1177, 0.7873, 0.3092],
        [0.0059, 0.3353, 0.4659],
        [0.0752, 0.1463, 0.2398]])

##### PyTorch处理的矩阵是tensor格式

生成全零矩阵

In [7]:
x = torch.zeros(5 , 3 , dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### 输出矩阵大小

In [9]:
x.size()

torch.Size([5, 3])

### view函数改变矩阵维度

In [10]:
x = torch.randn(4, 4) # 四行四列的矩阵
y = x.view(16) # 变为一个维度的向量
z = x.view(-1, 8) # 自动计算行数，给定列数为8列
print(x.size() , y.size() , z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 与Numpy协同操作

In [11]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)