### 线性回归(以y=2x+1为例)

In [8]:
import numpy as np
import torch
import torch.nn as nn

生成x向量

In [11]:
x = [i for i in range(11)]
x_train = np.array(x , dtype = np.float32)
x_train = x_train.reshape(-1 , 1)
print(x)
print(x_train)
print(x_train.shape)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
(11, 1)


生成y向量

In [12]:
y = [2 * i + 1 for i in range(11)]
y_train = np.array(y , dtype = np.float32)
y_train = y_train.reshape(-1 , 1)
print(y)
print(y_train)
print(y_train.shape)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
[[ 1.]
 [ 3.]
 [ 5.]
 [ 7.]
 [ 9.]
 [11.]
 [13.]
 [15.]
 [17.]
 [19.]
 [21.]]
(11, 1)


### 线性回归模型
- 线性回归就是不加激活函数的全连接层 

In [13]:
# 建立线性回归模型
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel , self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
    
    # 前向传播
    def forward(self , x):
        return self.linear(x)

In [19]:
input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim , output_dim)
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

指定参数和损失函数

In [20]:
epochs = 1000 # 迭代1000次
learning_rate = 0.01 # 学习率0.01

# 优化器SGD
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# 输入x和输出y的均方标准差
criterion = nn.MSELoss()

训练模型

In [21]:
for epoch in range(epochs):
    epoch += 1
    # 将array转为tensor格式
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    # 梯度要清零
    optimizer.zero_grad()
    
    # 正向传播
    outputs = model(inputs)
    
    # 计算损失
    loss = criterion(outputs, labels)
    
    # 反向传播
    loss.backward()
    
    # 更新权重数值
    optimizer.step()
    if epoch % 50 == 0:
        print(f'epoch：{epoch} , loss：{loss.item()}')

epoch：50 , loss：0.178928405046463
epoch：100 , loss：0.10205411165952682
epoch：150 , loss：0.058207955211400986
epoch：200 , loss：0.03319957107305527
epoch：250 , loss：0.01893576607108116
epoch：300 , loss：0.01080025639384985
epoch：350 , loss：0.006160068325698376
epoch：400 , loss：0.0035134630743414164
epoch：450 , loss：0.002003949601203203
epoch：500 , loss：0.0011429685400798917
epoch：550 , loss：0.0006518939044326544
epoch：600 , loss：0.0003718256775755435
epoch：650 , loss：0.00021207220561336726
epoch：700 , loss：0.00012095653801225126
epoch：750 , loss：6.898951687617227e-05
epoch：800 , loss：3.935064160032198e-05
epoch：850 , loss：2.2443535272032022e-05
epoch：900 , loss：1.2801246157323476e-05
epoch：950 , loss：7.301435289264191e-06
epoch：1000 , loss：4.164826350461226e-06


### 测试结果

In [22]:
res = model(torch.from_numpy(x_train).requires_grad_()).data.numpy()
res

array([[ 0.99620396],
       [ 2.9967506 ],
       [ 4.9972973 ],
       [ 6.997844  ],
       [ 8.998391  ],
       [10.998938  ],
       [12.999485  ],
       [15.000031  ],
       [17.000578  ],
       [19.001125  ],
       [21.00167   ]], dtype=float32)

In [23]:
# 读取
torch.save(model.state_dict() , 'autograd.pkl')

In [24]:
model.load_state_dict(torch.load('autograd.pkl'))

<All keys matched successfully>

### 使用GPU进行训练
- 将数据和模型传入cuda进行运行

In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

# 将array转为tensor格式
inputs = torch.from_numpy(x_train).to(device)
labels = torch.from_numpy(y_train).to(device)