### Tensor常见形式
- scalar:数值
- vector:向量
- matrix:矩阵
- n-dimensional tensor:高维数据

In [1]:
import torch
from torch import tensor

### Scalar

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
2 * x

tensor(84.)

### Vector

$\boldsymbol{v} = [v_{1} , v_{2} , ... , v_{n}]$

In [6]:
v = tensor([1.5 , -0.5 , 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [7]:
v.dim()

1

In [8]:
v.size()

torch.Size([3])

### Matrix

In [9]:
M = tensor([[1. , 2.] , [3. , 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [10]:
M.matmul(M) # M*M两个矩阵相乘

tensor([[ 7., 10.],
        [15., 22.]])

In [11]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

### n-dimensional tensor

- 多维矩阵